name: CICD

on:
  push:
    paths:
      - 'src/**'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Load .env
        run: |
          touch .env
          echo ADMIN_USER=${{ secrets.ADMIN_USER }} >> .env
          echo ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} >> .env

      - name: Generate keys
        run: make gen_keys

      - name: Run tests
        run: make test
