name: CICD

on:
  push:
    paths:
      - 'src/**'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Load .env
        run: |
          touch .env
          echo ADMIN_USER=${{ secrets.ADMIN_USER }} >> .env
          echo ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} >> .env
      - name: Generate keys
        run: make gen_keys

      - name: Run tests
        run: make test
  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: make build_windows

      - name: Run Azure Functions action
        uses: Azure/functions-action@v1
        with:
          app-name: bthreader-auth-server
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

